# Generated by Django 4.0.3 on 2022-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_user_userprofile_guestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
